### ISSUE TITLE
katalog poziadaviek

### ISSUE THREAD

**Issue by Yeeds** [TIS2017/GeneratorTestov#1]
Rozpracovaný katalóg požiadaviek je tu:

https://docs.google.com/document/d/1WzOcQ5Iq5V4BrKkncLLz7jsW66oMOGQNvw2UhbBHxeA/edit?usp=sharing

**Comment by andrejjursa** [comment]
@TIS2017/rmc ako pokracujete? podarilo sa skontaktovat zadavatelku?

**Comment by marianni** [comment]
@andrejjursa pokracujeme OK, zadavatelka odpisala uz v piatok , tak sme odpisali a cakame na odpoved. Dohadujeme sa na skype stretnuti.

**Comment by andrejjursa** [comment]
@tis2017/rmc Zdravim, nastal nejaky progress? Na githube v tejto veci nevidiet ziadnu aktivitu. Podarilo sa vam stretnut sa so zadavatelkou?

**Comment by Yeeds** [comment]
Cau, ano stretli sme sa s nou mame potrebne veci. Mame hotovy narvrh DB + technologie, ktore pouzijeme a aj nejaku graficku predstavu zadavatelky.

**Comment by andrejjursa** [comment]
@Yeeds to je vyborna sprava, a ako je na tom katalog poziadaviek (jak ten neuceleny - bod B zo zadania, tak uceleny - bod C)?

**Comment by andrejjursa** [comment]
@TIS2017/rmc  vidim, ze uz pracujete aj na navrhu, co je velke plus, ale kedy sa dospeje k ucelenemu katalogu, ktory mozem hodnotit? uz vas predbehla, hoci nie zrovna vitazne, druha skupina, ktora mala tiez meskanie

**Comment by milancifra** [comment]
@andrejjursa uz je skoro hotovy, v nedelu bude v gite

**Comment by andrejjursa** [comment]
@milancifra vyborne!

**Comment by andrejjursa** [comment]
@TIS2017/rmc ahojte, kedze vcera @milancifra nahodil na github katalog poziadaviek, dam vam k nemu pripomienky:

1. **sekcia 1.1** vyborne, asi najlepsie napisana spomedzi vsetkych mojich skupin :) 👍 ,
1. **sekcia 1.2** tiez vyborne, projekt je zdanlivo maleho rozsahu a tu je celkom slusne vystihnuta jeho podstata,
1. **sekcia 1.3** zadefinovane su iba skratky jazykov, technologii ci formatov, mozno by sa zisli aj ine typy skratiek ci definicii ak sa v dokumente vyskytuju (pozn. citam to odhora dolu a rovno pisem pripomienky), ak ale take definicie neexistuju, aspon k tym sucasnym skuste este popisa trochu viac, napr. ucel tych technologii,
1. **sekcia 1.4** v podstate ok, ked uz je to v skratkach, tak tam snad pridajte aj odkaz na php.net,
1. **sekcia 1.5** toto ma trochu pobavilo, v dobrom :), ale v skutocnosti sa takto prehlad dokumentu neuvadza:
    - nepopisuje sa tam aktualna sekcia, tj. 1 uvod,
    - ostatne sekcie sa tam oznacuju cislom a pise sa tam, co sa v nich nachadza par slovami, napriklad:
        `Sekcia dva dokumentu popisuje produkt z jeho perspektivy, funkcii, pouzivatelov, obmedzeni a zavislosti. V sekcii tri citatel najde podrobne poziadavky zadavatelky na realizaciu aplikacie.`
1. **sekcia 2.1** sice popisuje ake technologie sa planuju pouzit, ale dobre by bolo pridat este jeden mensi odstavec, ktory zhrnie v kratkosti na co bude aplikacia sluzit, aky ma ucel, to sa mysli hlavne tou perspektivou,
1. **sekcia 2.2** myslim, ze tu je pekne popisana zakladna funkcionalita aplikacie, zaujimave bude generovanie testu, co sa z tohoto textu da pochopit, ze ide o banalitu, ale pozor na to, toto bude skutocne najzlozitejsi problem v celej aplikacii, nakolko sa jedna o urcity druh optimalizacneho problemu, ktory sa neda riesit naivne, asi nie je nutne to do textu pisat, ja to tu spomynam len preto, aby ste mali na pamati, ze aplikacia sice vyzera rozsahom malinka ale tato konkretna cast vas moze dost potrapit,
1. **sekcia 2.3** tu asi nie je co dodat,
1. **sekcia 2.4** obsah sa kamsi zatulal? :),
1. **sekcia 2.5** v podstate ok, ale mozno by bolo na zvazenie uviest aj zavislost na konkretnej databaze, aj verzii a verziach php, node.js (neviem, ci toto treba, asi npm bude len na pridanie front-end zavislosti, ci?),
1. **sekcia 3** celkovo sa zda, ze su tu iba dve poziadavky, ktore bohuzial nie su scela zapisane, takze:
    - **R.1.2** cakal by som, ze by tu malo byt popisane aj co sa stane po odoslani formulara, napr. ked sa ulozi, kam sa presmeruje aplikacia (btw. preco R.1.2 ? zmazali ste R.1.1?),
    - **R.1.1** ktora tu chyba by som ocakaval, ze hovori nieco o zozname otazok, ktory predpokladam, ze aplikacia bude zobrazovat asi hned na home page (ak to tak mozme nazvat), cakal by som, ze by mala byt moznost otazky aj upravit ci vymazat
    - **R.1.3** by skor mohlo byt vysledkom **R.1.2** zapisane napr. ako **R.1.2.1 Uspesne pridanie otazky** a tam text o tom, ze aplikacia ponukne moznost opatovne vlozit dalsiu otazku po stlaceni tlacidla, pripadne navrat na zoznam otazok?, potom by sa asi hodila aj poziadavka **R.1.2.2 Zlyhanie pri ukladani** a tu popisat, co sa stane potom, ci sa zobrazi predvyplneny formular s datami, ktore sa nepodarilo ulozit alebo bude pouzivatel presmerovany na nejaku stranku, ktora ho informuje o nezdare, co sa bude diat potom, atd.,
    - celkovo **R.1** je nekompletne popisany proces spravy otazok a je treba ho doplnit o vsetky chybajuce podpoziadavky, mozno by sa cele **R.1** malo volat **Sprava otazok** a byt potom teda ako som uz pisal rozobrate na drobe podpoziadavky (tiez by bolo dobre nieco do **R.1** napisat, aspon mali odstavcek, zhrnutie, ze o co sa jedna v tejto poziadavke),
    - este vecsim problemom je poziadavka **R.2**, tu je skutocne nutne riadne vysvetlit v podpoziadavkach co sa stane ak je generovanie testu uspesne, co sa stane ak je neuspesne (ci to da len oznamenie alebo spolu s oznamenim sa zobrazi aj predvyplneny formular s datami, s ktorymi sa nepodarilo test zostavit, atd.), ci vygenerovane pdf bude niekde ulozene v databaze spolu s konfiguraciou testu (caching, napr.), ak sa ma stiahnut, je vobec nutne ho ukladat na server alebo ho staci podla konfiguracie testu takpovediac just-in-time vygenerovat a vratit na stiahnutie (proste nastavit patricne hlavicky s nazvom suboru, content-disposition a dalej len vratit v case stahovania vygenerovane telo dokumentu), pozn. preco medzi technologiami nie je spomenuta nejaka kniznica alebo externy software pouzity na generovanie pdf, asi by bolo zaujimave vediet na akom principe sa bude generovat (pre php je napr. celkom sikovna kniznica tcpdf, ktora prevadza html4.1+css2.3 myslim na pdf, mozno uz aj html5+css3, davno som ju nepouzival, tak presne uz neviem).

Chcem vas na zaver poprosit, aby ste priebezne upravili spomenute nedostatky, koniec-koncov vysledny dokument, az ho uznam za vhodny treba posielat na schvalenie zadavatelke. Dokument musi byt zapisany tak, aby aj nezainteresovana osoba plne porozumela, co je treba realizovat za dielo. Paci sa mi, ze vam ako jedinej skupine nemusim vytknut styl prejavu, nicmenej par formalnych problemov tu je:
1. sekcie sa cisluju bez bodky na zaver, tj. mame sekciu **1 Uvod** alebo **1.1 Ucel dokumentu**, vsimnite si ze bodka za posledne cislo sa nepise, nie je to oznacenie radovej cislovky,
1. zoznamy, ci uz maju odrazky alebo nie, by mali zacinat s malym pismenom (okrem pripadu, ak je prve slovo skratka ci samo je vlastne meno alebo je sucastou vlastneho mena), posledny prvok zoznamu by mal koncit bodkou, u vas v dokumente je mozno vidiet niekolko zoznamov a kazdy je pisany inak (ale pozitivne na tom je, ze to hovori o vasej spolupraci pri pisani dokumentu :) ),
1. cislovanie kapitol by malo byt aj v obsahu (table of contents) dokumentu.

Zaverom by som len dodal, ze ste odovzdali vcelku dobry prvy dokument, tak este zapracujte na upravach, dajte mi vediet, az to bude hotove a nahrane na githube, ak vsetko fixnete ako som popisal, tak verim, ze to uz bude cele spravne. V pripade otazok samozrejme piste, najlepsie tu v komentaroch tohoto issue a nezabudnite dat `@` mention tag s mojim acc. name.

**Comment by marianni** [comment]
Ahoj @andrejjursa . Finálna verzia katalogu poziadaviek je nahodena.

**Comment by andrejjursa** [comment]
@TIS2017/rmc myslim, ze uz je to v poriadku, poslite to cim skor Sikudovej, nech to schvali alebo spripomienkuje. Medzitym prosim skuste dopracovat aj navrh a zacnite spisovat testovacie scenare. V pripade otazok ma samozrejme hned kontaktujte.

POZN.: Sikudova by mi mala poslat tiez potvrdenie, ze katalog poziadaviek splna to co pozaduje.
