### ISSUE TITLE
Návrh

### ISSUE THREAD

**Issue by marianni** [TIS2017/GeneratorTestov#13]
Rozpracovaný dokument s návrhom je tu:

https://docs.google.com/document/d/1dCbf7wcy2VCr7FgFDxaPOseFU_njerxx1PnFp0tBBH8/edit#

**Comment by marianni** [comment]
https://docs.google.com/document/d/1dCbf7wcy2VCr7FgFDxaPOseFU_njerxx1PnFp0tBBH8/edit#

**Comment by milancifra** [comment]
ahoj @andrejjursa, je nahodena prva verzia navrhu, zatial bez UML diagramov.

**Comment by andrejjursa** [comment]
Ahojte @TIS2017/rmc, do dokumentu na google docs som vam pridal pripomienky, zapracujte ich prosim.
