### ISSUE TITLE
Testovacie scenáre

### ISSUE THREAD

**Issue by marianni** [TIS2017/GeneratorTestov#14]
Rozpracovaný dokument so scenármi je tu:

https://docs.google.com/document/d/1ZEZdFza219CnloFU9I5DMMxD7KNo0inqBUK-ei-Gfc4/edit?usp=sharing

**Comment by marianni** [comment]
Ahoj @andrejjursa prva verzia testovacich scenarov je nahodena v branchi Testovacie_scenare v priecinku dokumentacia

**Comment by andrejjursa** [comment]
@TIS2017/rmc iba letmo som to teraz pozrel, chyba mi tam pri kazdom testovacom scenary zoznam cisiel poziadaviek z katalogu, ktore tento scenar pokryva, prosim dodajte to tam, potom si pozrem cely dokument

**Comment by andrejjursa** [comment]
Ahojte @TIS2017/rmc, este raz vas prosim, aby ste do dokumentu doplnili referencne cisla poziadaviek z katalogu poziadaviek, aby bol dokument testovacich scenarov uplny.

**Comment by marianni** [comment]
Ahoj @andrejjursa , testovacie scenare upravene a vlozene cisla podla katalogu poziadaviek.
