### ISSUE TITLE
Otazka k implementacii

### ISSUE THREAD

**Issue by andrejjursa** [TIS2017/GeneratorTestov#15]
Zdravim vas @TIS2017/rmc.

Toto issue je v podsate len otazka. Pozeram, ze za cely cas od konca vyucbovej casti semestra nedoslo k jedinej implementacnej zmene na githube. Dufam, ze ste na niecom pocast poslednych dvoch tyzdnov pracovali, hoci tu k tomu nie je ziadne relevantne issue, branch ani nic ine. Rad by som vam pripomenul to, co som vam hovoril niekolko poslednych tyzdnov v semestri a to, ze implementacia vobec nemusi cakat na dokoncenie dokumentacie. Rad by som teda videl nejake vysledky vasej prace minimalne za posledny tyzden od noveho roku.

Dakujem za pochopenie.
Andrej

**Comment by marianni** [comment]
Ahoj @andrejjursa , na implementacii sa pracuje, ja finalizujem frontend uz a co sa tyka testovacich scenarov, dolozim cisla. 

S pozdravom
Marianna

**Comment by andrejjursa** [comment]
@marianni ok, to je dobra sprava, jediny problem je, ze vyvoj ma byt vidiet transparentne tu na githube, co sa nedeje u nikoho z vas, prosil by som, aby kazdy svoju pracu commitoval do repozitara na githube.
