### ISSUE TITLE
vytvorenie štruktúry projektu

### ISSUE THREAD

**Issue by milancifra** [TIS2017/GeneratorTestov#3]
Rozhodli sme sa pre PHP framework [Laravel](https://laravel.com/). Bude potrebné ho nahodiť a nakonfigurovať pre naše potreby.

**Comment by pavelpetrovic** [comment]
mate uz ucet na kempelenovi? potrebujete ucet na kempelenovi?

**Comment by milancifra** [comment]
@pavelpetrovic nie, nebudeme tam potrebovať účet.
